SUBROUTINE boundary
USE mdata
!!TEMPORARY VARIABLES
INTEGER OVER(30000),II(30000)
DOUBLE PRECISION XX(30000),YY(30000),UU(30000),VV(30000)
DOUBLE PRECISION DENDEN(30000),VISVIS(30000)


!!DELETING PARTICLES OUT OF THE BOUNDARY HIGHER THAN Y = 1.0 M
OVER=0
!!Changed by TongJ
DO I=1,N
 	IF(IFLAG(I)==2.AND.Y1(I)>Yup) OVER(I)=OVER(I)+1
END DO 
!!RE-NUMBERING PARTICLES
K=0
DO I=1,N
	IF(IFLAG(I)==2.AND.OVER(I)>=1)CYCLE
	K=K+1
	XX(K)=X1(I)
	YY(K)=Y1(I)
	UU(K)=U1(I)
	VV(K)=V1(I)
	II(K)=IFLAG(I)
	VISVIS(K)=VISEFF(I)
	DENDEN(K)=DEN0(I)
END DO
N=K
DO I=1,N
	X1(I)=XX(I)
	Y1(I)=YY(I)
	U1(I)=UU(I)
	V1(I)=VV(I)
	IFLAG(I)=II(I)
	VISEFF(I)=VISVIS(I)
	DEN0(I)=DENDEN(I)
END DO
	
RETURN
END SUBROUTINE boundary

