!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!    THIS SUBROUTINE ONLY NEEDS TO BE CHANGED AT THE SPECIFICATION OF PRESSURE   !!!!
!!!!    FOR DUMMY PARTICLES AT THE BEGINNING OF SUBROUTINE                          !!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!! UPDATE OF PARTICLE VELOCITY AND COORDINATES BY ENFORCING PRESSURE
SUBROUTINE	correct(ICHANGE)
USE mdata
!! INDICATION OF CHANGING TIME STEP
INTEGER ICHANGE
!! LOCAL VARIABLE-PRESSURE CHANGED VELOCITY AND ITS COMPONENTS OF DIFFERENT
!! KERNEL DISTANCES
DOUBLE PRECISION DU,DV,DUXX,DVYY
!! LOCAL VARIABLE-PARTICLE DISTANCE,RELATIVE DISTANCE
DOUBLE PRECISION R,Q
!! LOCAL VARIABLE-FOR COURANT CONDICTION
DOUBLE PRECISION A,B,DISTANCE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!	INITIALIZATION OF PRESSURE OF DUMMY PARTICLES-BY NEUMANN CONDICTION  !!
!!	PRESSURE OF FIRST LINE OF DUMMY PARTICLES                            !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!	CALCULATING MODIFIED VELOCITY BY PRESSURE   !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
DO I=1,NR
!!  EXCLUDING WALL PARTICLES - WALL PARTICLES DO NOT MOVE
    IF(IFLAG(REAP(I))==1.OR.IFLAG(REAP(I))==3) THEN
	    U2(REAP(I))=U1(REAP(I))
	    V2(REAP(I))=V1(REAP(I))
	    X2(REAP(I))=X1(REAP(I))
	    Y2(REAP(I))=Y1(REAP(I))
	    CYCLE
	END IF

!! COMPUTATION OF MOVABLE PARTICLES
!! INITIALIZATION OF CHANGED VELOCITY BY PRESSURE
DU=0.0
DV=0.0
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!	USING LINK LIST......               !!
!!	NEIGHBOUR PARTICELS IN CENTER GRID  !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IA=XSTAR(REAP(I))/(2.0*H)
JA=YSTAR(REAP(I))/(2.0*H)
    DO J=1,NLINK(IA,JA)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA,JA,J)))**2+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA,JA,J)))**2)
!!      EXCLUDING REFERENCE PARTICLE
	    IF(REAP(I)==LINK(IA,JA,J)) CYCLE
        !! AVOIDING SINGULARITY
	    IF(R<=(0.1*H)) R=0.1*H
!!      RELATIVE DISTANCE
	    Q=R/H
!!      USING DIFFERENT KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE 
        CYCLE
        END IF
    DUXX=-DT*PM(LINK(IA,JA,J))*DWDQ*(XSTAR(REAP(I))-XSTAR(LINK(IA,JA,J)))*&
         P(LINK(IA,JA,J))/(R*H*ROU(LINK(IA,JA,J))**2)-DT*PM(LINK(IA,JA,J))*&
         DWDQ*(XSTAR(REAP(I))-XSTAR(LINK(IA,JA,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)

    DVYY=-DT*PM(LINK(IA,JA,J))*DWDQ*(YSTAR(REAP(I))-YSTAR(LINK(IA,JA,J)))*&
         P(LINK(IA,JA,J))/(R*H*ROU(LINK(IA,JA,J))**2)-DT*PM(LINK(IA,JA,J))*&
         DWDQ*(YSTAR(REAP(I))-YSTAR(LINK(IA,JA,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)
	DU=DU+DUXX
	DV=DV+DVYY
    END DO
!!  NEIGHBOUR PARTICELS IN UPPER GRID
	DO J=1,NLINK(IA,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA,JA+1,J)))**2+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA,JA+1,J)))**2)
	    IF(REAP(I)==LINK(IA,JA+1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE 
        CYCLE
	    ENDIF
	DUXX=-DT*PM(LINK(IA,JA+1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA,JA+1,J)))*&
         P(LINK(IA,JA+1,J))/(R*H*ROU(LINK(IA,JA+1,J))**2)-&
         DT*PM(LINK(IA,JA+1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA,JA+1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)

    DVYY=-DT*PM(LINK(IA,JA+1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA,JA+1,J)))*&
         P(LINK(IA,JA+1,J))/(R*H*ROU(LINK(IA,JA+1,J))**2)-&
         DT*PM(LINK(IA,JA+1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA,JA+1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN LOWER GRID
	DO J=1,NLINK(IA,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA,JA-1,J)))**2+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA,JA-1,J)))**2)
	    IF(REAP(I)==LINK(IA,JA-1,J)) CYCLE
        IF(R<=(0.1*H)) R=0.1*H
    Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    ENDIF
	DUXX=-DT*PM(LINK(IA,JA-1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA,JA-1,J)))*&
         P(LINK(IA,JA-1,J))/(R*H*ROU(LINK(IA,JA-1,J))**2)-&
         DT*PM(LINK(IA,JA-1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA,JA-1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)

    DVYY=-DT*PM(LINK(IA,JA-1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA,JA-1,J)))*&
         P(LINK(IA,JA-1,J))/(R*H*ROU(LINK(IA,JA-1,J))**2)-&
         DT*PM(LINK(IA,JA-1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA,JA-1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO

!!	NEIGHBOUR PARTICELS IN LEFT GRID
	DO J=1,NLINK(IA-1,JA)
!!	PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA,J)))**2+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA,J)))**2)
	    IF(REAP(I)==LINK(IA-1,JA,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    ENDIF

	DUXX=-DT*PM(LINK(IA-1,JA,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA,J)))*&
         P(LINK(IA-1,JA,J))/(R*H*ROU(LINK(IA-1,JA,J))**2)-&
         DT*PM(LINK(IA-1,JA,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)

    DVYY=-DT*PM(LINK(IA-1,JA,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA,J)))*&
         P(LINK(IA-1,JA,J))/(R*H*ROU(LINK(IA-1,JA,J))**2)-&
         DT*PM(LINK(IA-1,JA,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN RIGHT GRID
	DO J=1,NLINK(IA+1,JA)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA,J)))**2+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA,J)))**2)
	    IF(REAP(I)==LINK(IA+1,JA,J)) CYCLE
        IF(R<=(0.1*H)) R=0.1*H
    Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PM(LINK(IA+1,JA,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA,J)))*&
         P(LINK(IA+1,JA,J))/(R*H*ROU(LINK(IA+1,JA,J))**2)-&
         DT*PM(LINK(IA+1,JA,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)

    DVYY=-DT*PM(LINK(IA+1,JA,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA,J)))*&
         P(LINK(IA+1,JA,J))/(R*H*ROU(LINK(IA+1,JA,J))**2)-&
         DT*PM(LINK(IA+1,JA,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN UPPER RIGHT GRID
	DO J=1,NLINK(IA+1,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA+1,J)))**2+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA+1,J)))**2)
	    IF(REAP(I)==LINK(IA+1,JA+1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PM(LINK(IA+1,JA+1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA+1,J)))*&
         P(LINK(IA+1,JA+1,J))/(R*H*ROU(LINK(IA+1,JA+1,J))**2)-&
         DT*PM(LINK(IA+1,JA+1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA+1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)

    DVYY=-DT*PM(LINK(IA+1,JA+1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA+1,J)))*&
         P(LINK(IA+1,JA+1,J))/(R*H*ROU(LINK(IA+1,JA+1,J))**2)-&
         DT*PM(LINK(IA+1,JA+1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA+1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN UPPER LEFT GRID
	DO J=1,NLINK(IA-1,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA+1,J)))**2+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA+1,J)))**2)
	    IF(REAP(I)==LINK(IA-1,JA+1,J)) CYCLE
        IF(R<=(0.1*H)) R=0.1*H
    Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PM(LINK(IA-1,JA+1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA+1,J)))*&
         P(LINK(IA-1,JA+1,J))/(R*H*ROU(LINK(IA-1,JA+1,J))**2)-&
         DT*PM(LINK(IA-1,JA+1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA+1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)

    DVYY=-DT*PM(LINK(IA-1,JA+1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA+1,J)))*&
         P(LINK(IA-1,JA+1,J))/(R*H*ROU(LINK(IA-1,JA+1,J))**2)-&
         DT*PM(LINK(IA-1,JA+1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA+1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN LOWER RIGHT GRID
	DO J=1,NLINK(IA+1,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA-1,J)))**2+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA-1,J)))**2)
	    IF(REAP(I)==LINK(IA+1,JA-1,J)) CYCLE
        IF(R<=(0.1*H)) R=0.1*H
    Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PM(LINK(IA+1,JA-1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA-1,J)))*&
         P(LINK(IA+1,JA-1,J))/(R*H*ROU(LINK(IA+1,JA-1,J))**2)-&
         DT*PM(LINK(IA+1,JA-1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA-1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)

    DVYY=-DT*PM(LINK(IA+1,JA-1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA-1,J)))*&
         P(LINK(IA+1,JA-1,J))/(R*H*ROU(LINK(IA+1,JA-1,J))**2)-&
         DT*PM(LINK(IA+1,JA-1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA-1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN LOWER LEFT GRID
	DO J=1,NLINK(IA-1,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA-1,J)))**2+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA-1,J)))**2)
	    IF(REAP(I)==LINK(IA-1,JA-1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    ENDIF
	DUXX=-DT*PM(LINK(IA-1,JA-1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA-1,J)))*&
         P(LINK(IA-1,JA-1,J))/(R*H*ROU(LINK(IA-1,JA-1,J))**2)-&
         DT*PM(LINK(IA-1,JA-1,J))*DWDQ*&
         (XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA-1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)

    DVYY=-DT*PM(LINK(IA-1,JA-1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA-1,J)))*&
         P(LINK(IA-1,JA-1,J))/(R*H*ROU(LINK(IA-1,JA-1,J))**2)-&
         DT*PM(LINK(IA-1,JA-1,J))*DWDQ*&
         (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA-1,J)))*P(REAP(I))/(R*H*ROU(REAP(I))**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!	USING DUMMY PARTICLES  !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	DO J=1,NLINKDUMMY(IA,JA)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-X1(LINKDUMMY(IA,JA,J)))**2+&
          (YSTAR(REAP(I))-Y1(LINKDUMMY(IA,JA,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    ENDIF
	DUXX=-DT*PMD*DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA,JA,J)))*&
         P(LINKDUMMY(IA,JA,J))/(R*H*1000.0**2)-DT*PMD*DWDQ*&
         (XSTAR(REAP(I))-X1(LINKDUMMY(IA,JA,J)))*P(REAP(I))/(R*H*1000.0**2)

    DVYY=-DT*PMD*DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA,JA,J)))*&
         P(LINKDUMMY(IA,JA,J))/(R*H*1000.0**2)-DT*PMD*DWDQ*&
         (YSTAR(REAP(I))-Y1(LINKDUMMY(IA,JA,J)))*P(REAP(I))/(R*H*1000.0**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN UPPER GRID
	DO J=1,NLINKDUMMY(IA,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-X1(LINKDUMMY(IA,JA+1,J)))**2+&
          (YSTAR(REAP(I))-Y1(LINKDUMMY(IA,JA+1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	    Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PMD*DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA,JA+1,J)))*&
         P(LINKDUMMY(IA,JA+1,J))/(R*H*1000.0**2)-DT*PMD*DWDQ*&
         (XSTAR(REAP(I))-X1(LINKDUMMY(IA,JA+1,J)))*P(REAP(I))/(R*H*1000.0**2)

    DVYY=-DT*PMD*DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA,JA+1,J)))*&
         P(LINKDUMMY(IA,JA+1,J))/(R*H*1000.0**2)-DT*PMD*DWDQ*&
         (YSTAR(REAP(I))-Y1(LINKDUMMY(IA,JA+1,J)))*P(REAP(I))/(R*H*1000.0**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!	NEIGHBOUR PARTICELS IN LOWER GRID
	DO J=1,NLINKDUMMY(IA,JA-1)
!!	PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-X1(LINKDUMMY(IA,JA-1,J)))**2+&
          (YSTAR(REAP(I))-Y1(LINKDUMMY(IA,JA-1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PMD*DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA,JA-1,J)))*&
         P(LINKDUMMY(IA,JA-1,J))/(R*H*1000.0**2)-DT*PMD*DWDQ*&
         (XSTAR(REAP(I))-X1(LINKDUMMY(IA,JA-1,J)))*P(REAP(I))/(R*H*1000.0**2)

    DVYY=-DT*PMD*DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA,JA-1,J)))*&
         P(LINKDUMMY(IA,JA-1,J))/(R*H*1000.0**2)-DT*PMD*DWDQ*&
         (YSTAR(REAP(I))-Y1(LINKDUMMY(IA,JA-1,J)))*P(REAP(I))/(R*H*1000.0**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN LEFT GRID
	DO J=1,NLINKDUMMY(IA-1,JA)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-X1(LINKDUMMY(IA-1,JA,J)))**2+&
          (YSTAR(REAP(I))-Y1(LINKDUMMY(IA-1,JA,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PMD*DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA-1,JA,J)))*&
         P(LINKDUMMY(IA-1,JA,J))/(R*H*1000.0**2)-DT*PMD*DWDQ*&
         (XSTAR(REAP(I))-X1(LINKDUMMY(IA-1,JA,J)))*P(REAP(I))/(R*H*1000.0**2)

    DVYY=-DT*PMD*DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA-1,JA,J)))*&
         P(LINKDUMMY(IA-1,JA,J))/(R*H*1000.0**2)-DT*PMD*DWDQ*&
         (YSTAR(REAP(I))-Y1(LINKDUMMY(IA-1,JA,J)))*P(REAP(I))/(R*H*1000.0**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN RIGHT GRID
	DO J=1,NLINKDUMMY(IA+1,JA)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-X1(LINKDUMMY(IA+1,JA,J)))**2+&
          (YSTAR(REAP(I))-Y1(LINKDUMMY(IA+1,JA,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PMD*DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA+1,JA,J)))*&
         P(LINKDUMMY(IA+1,JA,J))/(R*H*1000.0**2)-DT*PMD*DWDQ*&
         (XSTAR(REAP(I))-X1(LINKDUMMY(IA+1,JA,J)))*P(REAP(I))/(R*H*1000.0**2)

    DVYY=-DT*PMD*DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA+1,JA,J)))*&
         P(LINKDUMMY(IA+1,JA,J))/(R*H*1000.0**2)-DT*PMD*DWDQ*&
         (YSTAR(REAP(I))-Y1(LINKDUMMY(IA+1,JA,J)))*P(REAP(I))/(R*H*1000.0**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN UPPER RIGHT GRID
	DO J=1,NLINKDUMMY(IA+1,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-X1(LINKDUMMY(IA+1,JA+1,J)))**2+&
          (YSTAR(REAP(I))-Y1(LINKDUMMY(IA+1,JA+1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PMD*DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA+1,JA+1,J)))*&
         P(LINKDUMMY(IA+1,JA+1,J))/(R*H*1000.0**2)-DT*PMD*&
         DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA+1,JA+1,J)))*P(REAP(I))/&
         (R*H*1000.0**2)

    DVYY=-DT*PMD*DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA+1,JA+1,J)))*&
         P(LINKDUMMY(IA+1,JA+1,J))/(R*H*1000.0**2)-DT*PMD*&
         DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA+1,JA+1,J)))*P(REAP(I))/&
         (R*H*1000.0**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN UPPER LEFT GRID
	DO J=1,NLINKDUMMY(IA-1,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-X1(LINKDUMMY(IA-1,JA+1,J)))**2+&
          (YSTAR(REAP(I))-Y1(LINKDUMMY(IA-1,JA+1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	    Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PMD*DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA-1,JA+1,J)))*&
         P(LINKDUMMY(IA-1,JA+1,J))/(R*H*1000.0**2)-DT*PMD*&
         DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA-1,JA+1,J)))*P(REAP(I))/&
         (R*H*1000.0**2)
    DVYY=-DT*PMD*DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA-1,JA+1,J)))*&
         P(LINKDUMMY(IA-1,JA+1,J))/(R*H*1000.0**2)-DT*PMD*&
         DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA-1,JA+1,J)))*P(REAP(I))/&
         (R*H*1000.0**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN LOWER RIGHT GRID
	DO J=1,NLINKDUMMY(IA+1,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-X1(LINKDUMMY(IA+1,JA-1,J)))**2+&
          (YSTAR(REAP(I))-Y1(LINKDUMMY(IA+1,JA-1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PMD*DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA+1,JA-1,J)))*&
         P(LINKDUMMY(IA+1,JA-1,J))/(R*H*1000.0**2)-DT*PMD*&
         DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA+1,JA-1,J)))*P(REAP(I))/&
         (R*H*1000.0**2)

    DVYY=-DT*PMD*DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA+1,JA-1,J)))*&
         P(LINKDUMMY(IA+1,JA-1,J))/(R*H*1000.0**2)-DT*PMD*&
         DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA+1,JA-1,J)))*P(REAP(I))/&
         (R*H*1000.0**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO
!!  NEIGHBOUR PARTICELS IN LOWER LEFT GRID
	DO J=1,NLINKDUMMY(IA-1,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-X1(LINKDUMMY(IA-1,JA-1,J)))**2+&
          (YSTAR(REAP(I))-Y1(LINKDUMMY(IA-1,JA-1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	DUXX=-DT*PMD*DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA-1,JA-1,J)))*&
         P(LINKDUMMY(IA-1,JA-1,J))/(R*H*1000.0**2)-DT*PMD*&
         DWDQ*(XSTAR(REAP(I))-X1(LINKDUMMY(IA-1,JA-1,J)))*P(REAP(I))/&
         (R*H*1000.0**2)

    DVYY=-DT*PMD*DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA-1,JA-1,J)))*&
         P(LINKDUMMY(IA-1,JA-1,J))/(R*H*1000.0**2)-DT*PMD*&
         DWDQ*(YSTAR(REAP(I))-Y1(LINKDUMMY(IA-1,JA-1,J)))*P(REAP(I))/&
         (R*H*1000.0**2)
	DU=DU+DUXX
	DV=DV+DVYY
	END DO

!!  MODIFICATION OF SURFACE PARTICLES
	IF(DENSTAR(REAP(I))<=ROUWATER) THEN
	DU=DU*2.0
	DV=DV*2.0
	END IF

!!CALCULATING PARTICLE VELOCITY OF TIME T PLUS 1
U2(REAP(I))=USTAR(REAP(I))+DU
V2(REAP(I))=VSTAR(REAP(I))+DV
END DO


!!COMPUTATION OF MOVABLE PARTICLE POSITION OF TIME T PLUS 1
DO I=1,N
	IF(IFLAG(I)==2) THEN
	X2(I)=X1(I)+0.5*(U1(I)+U2(I))*DT
	Y2(I)=Y1(I)+0.5*(V1(I)+V2(I))*DT
!!  CHECK COURANT CONDICTION
	A=X2(I)-X1(I)
	B=Y2(I)-Y1(I)
	DISTANCE=SQRT(A*A+B*B)
	    IF(DISTANCE>ALPHA*Sp) THEN
	    WRITE(*,*) "TIME STEP FAST IN CORRECTION! RETURN AND RESET DT!"
!!	    WRITE(*,*) x1(REAP(I)),y1(REAP(I)),x2(REAP(I)),y2(REAP(I))
	    ICHANGE=1
	    RETURN
	    END IF
    ELSE
    X2(I)=X1(I)
    Y2(I)=Y1(I)
	END IF
END DO

!!END OF CORRECTION STEP
RETURN
END SUBROUTINE correct