!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!	       DENSITY OF INITIAL STEP       !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SUBROUTINE density0
USE MDATA
!! PARTICLE DISTANCE AND RELATIVE DISTANCE
DOUBLE PRECISION R,Q
!! LOOP
DO I=1,NR
!! INITIALIZATION OF EACH PARTICLE DENSITY
DEN0(REAP(I))=0.0
!! DENSITY CALCULATION BY NEIGHBOURING PARTICLES INCLUDING ITSELF THROUGH
!! KERNEL
!! NEIGHBOUR PARTICELS IN CENTER GRID
IA=X1(REAP(I))/(2.0*H)
JA=Y1(REAP(I))/(2.0*H)
	DO J=1,NLINK(IA,JA)
!! PARTICLE DISTANCE
    R=SQRT((X1(REAP(I))-X1(LINK(IA,JA,J)))*&
          (X1(REAP(I))-X1(LINK(IA,JA,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA,JA,J)))*&
          (Y1(REAP(I))-Y1(LINK(IA,JA,J))))
	Q=R/H
	    IF(REAP(I)==LINK(IA,JA,J)) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(REAP(I))
        CYCLE
	    END IF
!! USING DIFFERENT KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(LINK(IA,JA,J))
	    ELSEIF(Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/&
                (28.0*3.1408*H*H)*PM(LINK(IA,JA,J))
        ELSE
	    END IF
	END DO
!!	NEIGHBOUR PARTICELS IN UPPER GRID
	DO J=1,NLINK(IA,JA+1)
!!	PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA,JA+1,J)))*&
          (X1(REAP(I))-X1(LINK(IA,JA+1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA,JA+1,J)))*&
          (Y1(REAP(I))-Y1(LINK(IA,JA+1,J))))
	Q=R/H
	    IF(REAP(I)==LINK(IA,JA+1,J))THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(REAP(I))
        CYCLE
	    END IF
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(LINK(IA,JA+1,J))
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/&
                (28.0*3.1408*H*H)*PM(LINK(IA,JA+1,J))
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN LOWER GRID
	DO J=1,NLINK(IA,JA-1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA,JA-1,J)))*&
          (X1(REAP(I))-X1(LINK(IA,JA-1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA,JA-1,J)))*&
          (Y1(REAP(I))-Y1(LINK(IA,JA-1,J))))
	Q=R/H
	    IF(REAP(I)==LINK(IA,JA-1,J))THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(REAP(I))
        CYCLE
	    END IF
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0)THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(LINK(IA,JA-1,J))
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/&
                (28.0*3.1408*H*H)*PM(LINK(IA,JA-1,J))
        ELSE
	    END IF
    END DO
!!	NEIGHBOUR PARTICELS IN LEFT GRID
	DO J=1,NLINK(IA-1,JA)
!!	PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA-1,JA,J)))*&
          (X1(REAP(I))-X1(LINK(IA-1,JA,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA-1,JA,J)))*&
          (Y1(REAP(I))-Y1(LINK(IA-1,JA,J))))
	Q=R/H
	    IF(REAP(I)==LINK(IA-1,JA,J))THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(REAP(I))
        CYCLE
	    END IF
!!	USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(LINK(IA-1,JA,J))
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/&
                (28.0*3.1408*H*H)*PM(LINK(IA-1,JA,J))
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN RIGHT GRID
	DO J=1,NLINK(IA+1,JA)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA+1,JA,J)))*&
          (X1(REAP(I))-X1(LINK(IA+1,JA,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA+1,JA,J)))*&
          (Y1(REAP(I))-Y1(LINK(IA+1,JA,J))))
	Q=R/H
	    IF(REAP(I)==LINK(IA+1,JA,J))THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(REAP(I))
        CYCLE
	    END IF
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(LINK(IA+1,JA,J))
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/&
                (28.0*3.1408*H*H)*PM(LINK(IA+1,JA,J))
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN UPPER RIGHT GRID
	DO J=1,NLINK(IA+1,JA+1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA+1,JA+1,J)))*&
          (X1(REAP(I))-X1(LINK(IA+1,JA+1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA+1,JA+1,J)))*&
          (Y1(REAP(I))-Y1(LINK(IA+1,JA+1,J))))
	Q=R/H
	    IF(REAP(I)==LINK(IA+1,JA+1,J))THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(REAP(I))
        CYCLE
	    END IF
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(LINK(IA+1,JA+1,J))
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/&
                (28.0*3.1408*H*H)*PM(LINK(IA+1,JA+1,J))
        ELSE
	    END IF
	END DO
!1 NEIGHBOUR PARTICELS IN UPPER LEFT GRID
	DO J=1,NLINK(IA-1,JA+1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA-1,JA+1,J)))*&
          (X1(REAP(I))-X1(LINK(IA-1,JA+1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA-1,JA+1,J)))*&
          (Y1(REAP(I))-Y1(LINK(IA-1,JA+1,J))))
	Q=R/H
	    IF(REAP(I)==LINK(IA-1,JA+1,J)) 	THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(REAP(I))
        CYCLE
	    END IF
!!	USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(LINK(IA-1,JA+1,J))
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/&
                (28.0*3.1408*H*H)*PM(LINK(IA-1,JA+1,J))
        ELSE
	    END IF
    END DO
!! NEIGHBOUR PARTICELS IN LOWER RIGHT GRID
	DO J=1,NLINK(IA+1,JA-1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA+1,JA-1,J)))*&
          (X1(REAP(I))-X1(LINK(IA+1,JA-1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA+1,JA-1,J)))*&
          (Y1(REAP(I))-Y1(LINK(IA+1,JA-1,J))))
	Q=R/H
	    IF(REAP(I)==LINK(IA+1,JA-1,J)) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(REAP(I))
        CYCLE
	    END IF
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(LINK(IA+1,JA-1,J))
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/&
                (28.0*3.1408*H*H)*PM(LINK(IA+1,JA-1,J))
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN LOWER LEFT GRID
	DO J=1,NLINK(IA-1,JA-1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA-1,JA-1,J)))*&
          (X1(REAP(I))-X1(LINK(IA-1,JA-1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA-1,JA-1,J)))*&
          (Y1(REAP(I))-Y1(LINK(IA-1,JA-1,J))))
	Q=R/H
	    IF(REAP(I)==LINK(IA-1,JA-1,J)) 	THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(REAP(I))
        CYCLE
	    END IF
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/&
                (7.0*3.1408*H*H)*PM(LINK(IA-1,JA-1,J))
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/&
                (28.0*3.1408*H*H)*PM(LINK(IA-1,JA-1,J))
        ELSE
	    END IF
	END DO

!! CONSIDERING DUMMY PARTICLES BESIDE WALL BOUNDARY
!! NEIGHBOUR PARTICELS IN CENTER GRID
	DO J=1,NLINKDUMMY(IA,JA)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA,JA,J)))*&
          (X1(REAP(I))-X1(LINKDUMMY(IA,JA,J)))+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA,J)))*&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA,J))))
	Q=R/H
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/(7.0*3.1408*H*H)*PMD
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/(28.0*3.1408*H*H)*PMD
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN UPPER GRID
	DO J=1,NLINKDUMMY(IA,JA+1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA,JA+1,J)))*&
          (X1(REAP(I))-X1(LINKDUMMY(IA,JA+1,J)))+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA+1,J)))*&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA+1,J))))
	Q=R/H
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/(7.0*3.1408*H*H)*PMD
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/(28.0*3.1408*H*H)*PMD
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN LOWER GRID
	DO J=1,NLINKDUMMY(IA,JA-1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA,JA-1,J)))*&
          (X1(REAP(I))-X1(LINKDUMMY(IA,JA-1,J)))+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA-1,J)))*&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA-1,J))))
	Q=R/H
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/(7.0*3.1408*H*H)*PMD
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/(28.0*3.1408*H*H)*PMD
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN LEFT GRID
	DO J=1,NLINKDUMMY(IA-1,JA)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA-1,JA,J)))*&
          (X1(REAP(I))-X1(LINKDUMMY(IA-1,JA,J)))+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA,J)))*&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA,J))))
	Q=R/H
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/(7.0*3.1408*H*H)*PMD
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/(28.0*3.1408*H*H)*PMD
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN RIGHT GRID
	DO J=1,NLINKDUMMY(IA+1,JA)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA+1,JA,J)))*&
          (X1(REAP(I))-X1(LINKDUMMY(IA+1,JA,J)))+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA,J)))*&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA,J))))
	Q=R/H
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/(7.0*3.1408*H*H)*PMD
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/(28.0*3.1408*H*H)*PMD
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN UPPER RIGHT GRID
	DO J=1,NLINKDUMMY(IA+1,JA+1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA+1,JA+1,J)))*&
          (X1(REAP(I))-X1(LINKDUMMY(IA+1,JA+1,J)))+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA+1,J)))*&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA+1,J))))
	Q=R/H
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/(7.0*3.1408*H*H)*PMD
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/(28.0*3.1408*H*H)*PMD
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN UPPER LEFT GRID
	DO J=1,NLINKDUMMY(IA-1,JA+1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA-1,JA+1,J)))*&
          (X1(REAP(I))-X1(LINKDUMMY(IA-1,JA+1,J)))+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA+1,J)))*&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA+1,J))))
	Q=R/H
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/(7.0*3.1408*H*H)*PMD
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/(28.0*3.1408*H*H)*PMD
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN LOWER RIGHT GRID
	DO J=1,NLINKDUMMY(IA+1,JA-1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA+1,JA-1,J)))*&
          (X1(REAP(I))-X1(LINKDUMMY(IA+1,JA-1,J)))+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA-1,J)))*&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA-1,J))))
	Q=R/H
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/(7.0*3.1408*H*H)*PMD
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/(28.0*3.1408*H*H)*PMD
        ELSE
	    END IF
	END DO
!! NEIGHBOUR PARTICELS IN LOWER LEFT GRID
	DO J=1,NLINKDUMMY(IA-1,JA-1)
!! PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA-1,JA-1,J)))*&
          (X1(REAP(I))-X1(LINKDUMMY(IA-1,JA-1,J)))+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA-1,J)))*&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA-1,J))))
	Q=R/H
!! USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(1.-1.5*Q*Q+0.75*Q*Q*Q)/(7.0*3.1408*H*H)*PMD
	    ELSEIF (Q>1.0.AND.Q<=2.0) THEN
	    DEN0(REAP(I))=DEN0(REAP(I))+10.*(2.-Q)*(2.-Q)*(2.-Q)/(28.0*3.1408*H*H)*PMD
        ELSE
	    END IF
	END DO
END DO
RETURN
END SUBROUTINE density0