!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!   THIS SUBROUTINE DOES NOT NEED TO BE CHANGED   !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!PARTICLE LINKLIST AT PREVIOUS STEP
SUBROUTINE linklist1
USE mdata

NR=0
ND=0
DO I=1,N
    IF(IFLAG(I)/=0) THEN
    NR=NR+1
    REAP(NR)=I
    ELSE
    ND=ND+1
    DUMP(ND)=I
    END IF
ENDDO
!!INITIALIZATION OF GRID POINTS
NLINK=0
NLINKDUMMY=0
!!ALLOCATING PARTICLES AND ESTABLISHING LINK LIST
!!OPEN(1,FILE='O.DAT')
DO K=1,NR
    I=INT(X1(REAP(K))/(2.0*H))
	J=INT(Y1(REAP(K))/(2.0*H))
	NLINK(I,J)=NLINK(I,J)+1
	LINK(I,J,NLINK(I,J))=REAP(K)
!!    WRITE(1,*) K,I,J,NLINK(I,J)
END DO
!!	ALLOCATING PARTICLES AND ESTABLISHING LINK LIST
!! OPEN(1,FILE='O.DAT')
DO K=1,ND
    I=INT(X1(DUMP(K))/(2.0*H))
	J=INT(Y1(DUMP(K))/(2.0*H))
	NLINKDUMMY(I,J)=NLINKDUMMY(I,J)+1
	LINKDUMMY(I,J,NLINKDUMMY(I,J))=DUMP(K)
    !! WRITE(1,*) K,I,J,NLINKDUMMY(I,J)
END DO
!! CLOSE(1)
RETURN
!!CLOSE(1)
RETURN
END SUBROUTINE linklist1