!!PARTICLE LINKLIST AT INTERMEDIATE STEP
SUBROUTINE linklist2
USE mdata
!!INITIALIZATION OF GRID POINTS
NLINK=0
!!ALLOCATING PARTICLES AND ESTABLISHING LINK LIST
DO K=1,NR
I=INT(XSTAR(REAP(K))/(2.0*H))
J=INT(YSTAR(REAP(K))/(2.0*H))
NLINK(I,J)=NLINK(I,J)+1
LINK(I,J,NLINK(I,J))=REAP(K)
END DO
RETURN
END SUBROUTINE linklist2