!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  THIS SUBROUTINE DOES NOT NEED TO BE CHANGED  !!   
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SUBROUTINE predict(ICHANGE)
USE mdata
!! INDICATION OF CHANGING TIME STEP
INTEGER ICHANGE
!! CHANGED VELOCITY BY VISCOSITY
DOUBLE PRECISION DUVIS(N),DVVIS(N)
!! PARTICLE DISTANCE AND RELATIVE DISTANCE
DOUBLE PRECISION R,Q
!! LOCAL VARIABLE-KERNEL GRADIENT
DOUBLE PRECISION DWDQ
!! LOCAL VARIABLES-FOR COURANT CONDICTION
DOUBLE PRECISION A,B,DISTANCE
!! TEMPORAL VARIABLE - FOR CALCULATING STRAIN IN X AND Y DIRECTION
DOUBLE PRECISION AX,BX,CX,AY,BY,CY

!! PREDICTION OF TEMPORAL VELOCTIY AND COORDINATES
DO I=1,NR
!! EXCLUDING WALL PARTICLES - WALL PARTICLES DO NOT MOVE
    IF(IFLAG(REAP(I))==1.OR.IFLAG(REAP(I))==3) THEN
	USTAR(REAP(I))=U1(REAP(I))
	VSTAR(REAP(I))=V1(REAP(I))
	XSTAR(REAP(I))=X1(REAP(I))
	YSTAR(REAP(I))=Y1(REAP(I))
    CYCLE
	END IF
!! INITIALIZATION OF CHANGED VELOCITY
DUVIS(REAP(I))=0.0
DVVIS(REAP(I))=0.0

!! COMPUTATION OF CHANGED VELOCITY BY VISCOSITY
!! NEIGHBOUR PARTICELS IN CENTER GRID
IA=X1(REAP(I))/(2.0*H)
JA=Y1(REAP(I))/(2.0*H)
	DO J=1,NLINK(IA,JA)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA,JA,J)))*(X1(REAP(I))-X1(LINK(IA,JA,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA,JA,J)))*(Y1(REAP(I))-Y1(LINK(IA,JA,J))))
!!  EXCLUDING REFERENCE PARTICLE
	    IF(REAP(I)==LINK(IA,JA,J)) CYCLE
!!  AVOIDING SIGULARITY
	    IF(R<=(0.1*H)) R=0.1*H
!!  RELATIVE DISTANCE
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    ENDIF
!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))-U1(LINK(IA,JA,J))
	BX=(U1(REAP(I))-U1(LINK(IA,JA,J)))*(X1(REAP(I))-X1(LINK(IA,JA,J)))*&
       (X1(REAP(I))-X1(LINK(IA,JA,J)))/(R*R)
	CX=(V1(REAP(I))-V1(LINK(IA,JA,J)))*(X1(REAP(I))-X1(LINK(IA,JA,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA,JA,J)))/(R*R)

	AY=V1(REAP(I))-V1(LINK(IA,JA,J))
	BY=(V1(REAP(I))-V1(LINK(IA,JA,J)))*(Y1(REAP(I))-Y1(LINK(IA,JA,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA,JA,J)))/(R*R)
	CY=(U1(REAP(I))-U1(LINK(IA,JA,J)))*(X1(REAP(I))-X1(LINK(IA,JA,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA,JA,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES

	DUVIS(REAP(I))=DUVIS(REAP(I))+PM(LINK(IA,JA,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA,JA,J)))**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA,JA,J))+VIS0)*ROU(LINK(IA,JA,J)))

	DVVIS(REAP(I))=DVVIS(REAP(I))+PM(LINK(IA,JA,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA,JA,J)))**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA,JA,J))+VIS0)*ROU(LINK(IA,JA,J)))
	END DO

!!  NEIGHBOUR PARTICELS IN UPPER GRID
	DO J=1,NLINK(IA,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA,JA+1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA,JA+1,J)))*(Y1(REAP(I))-Y1(LINK(IA,JA+1,J))))
	    IF(REAP(I)==LINK(IA,JA+1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF
!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))-U1(LINK(IA,JA+1,J))
	BX=(U1(REAP(I))-U1(LINK(IA,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA,JA+1,J)))*&
       (X1(REAP(I))-X1(LINK(IA,JA+1,J)))/(R*R)
	CX=(V1(REAP(I))-V1(LINK(IA,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA,JA+1,J)))/(R*R)

	AY=V1(REAP(I))-V1(LINK(IA,JA+1,J))
	BY=(V1(REAP(I))-V1(LINK(IA,JA+1,J)))*(Y1(REAP(I))-Y1(LINK(IA,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA,JA+1,J)))/(R*R)
	CY=(U1(REAP(I))-U1(LINK(IA,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA,JA+1,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PM(LINK(IA,JA+1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA,JA+1,J)))**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA,JA+1,J))+VIS0)*ROU(LINK(IA,JA+1,J)))

	DVVIS(REAP(I))=DVVIS(REAP(I))+PM(LINK(IA,JA+1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA,JA+1,J)))**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA,JA+1,J))+VIS0)*ROU(LINK(IA,JA+1,J)))

	END DO
!!  NEIGHBOUR PARTICELS IN LOWER GRID
	DO J=1,NLINK(IA,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA,JA-1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA,JA-1,J)))*(Y1(REAP(I))-Y1(LINK(IA,JA-1,J))))
	    IF(REAP(I)==LINK(IA,JA-1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF
!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))-U1(LINK(IA,JA-1,J))
	BX=(U1(REAP(I))-U1(LINK(IA,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA,JA-1,J)))*&
       (X1(REAP(I))-X1(LINK(IA,JA-1,J)))/(R*R)
	CX=(V1(REAP(I))-V1(LINK(IA,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA,JA-1,J)))/(R*R)

	AY=V1(REAP(I))-V1(LINK(IA,JA-1,J))
	BY=(V1(REAP(I))-V1(LINK(IA,JA-1,J)))*(Y1(REAP(I))-Y1(LINK(IA,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA,JA-1,J)))/(R*R)
	CY=(U1(REAP(I))-U1(LINK(IA,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA,JA-1,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PM(LINK(IA,JA-1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA,JA-1,J)))**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA,JA-1,J))+VIS0)*ROU(LINK(IA,JA-1,J)))

	DVVIS(REAP(I))=DVVIS(REAP(I))+PM(LINK(IA,JA-1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA,JA-1,J)))**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA,JA-1,J))+VIS0)*ROU(LINK(IA,JA-1,J)))

	END DO
!!  NEIGHBOUR PARTICELS IN LEFT GRID
	DO J=1,NLINK(IA-1,JA)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA-1,JA,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA-1,JA,J)))*(Y1(REAP(I))-Y1(LINK(IA-1,JA,J))))
	    IF(REAP(I)==LINK(IA-1,JA,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF
!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))-U1(LINK(IA-1,JA,J))
	BX=(U1(REAP(I))-U1(LINK(IA-1,JA,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA,J)))*&
       (X1(REAP(I))-X1(LINK(IA-1,JA,J)))/(R*R)
	CX=(V1(REAP(I))-V1(LINK(IA-1,JA,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA-1,JA,J)))/(R*R)

	AY=V1(REAP(I))-V1(LINK(IA-1,JA,J))
	BY=(V1(REAP(I))-V1(LINK(IA-1,JA,J)))*(Y1(REAP(I))-Y1(LINK(IA-1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA-1,JA,J)))/(R*R)
	CY=(U1(REAP(I))-U1(LINK(IA-1,JA,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA-1,JA,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PM(LINK(IA-1,JA,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA-1,JA,J)))**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA-1,JA,J))+VIS0)*ROU(LINK(IA-1,JA,J)))

	DVVIS(REAP(I))=DVVIS(REAP(I))+PM(LINK(IA-1,JA,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA-1,JA,J)))**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA-1,JA,J))+VIS0)*ROU(LINK(IA-1,JA,J)))

	END DO
!!  NEIGHBOUR PARTICELS IN RIGHT GRID
	DO J=1,NLINK(IA+1,JA)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA+1,JA,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA+1,JA,J)))*(Y1(REAP(I))-Y1(LINK(IA+1,JA,J))))
	    IF(REAP(I)==LINK(IA+1,JA,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    ENDIF
!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))-U1(LINK(IA+1,JA,J))
	BX=(U1(REAP(I))-U1(LINK(IA+1,JA,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA,J)))*&
       (X1(REAP(I))-X1(LINK(IA+1,JA,J)))/(R*R)
	CX=(V1(REAP(I))-V1(LINK(IA+1,JA,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA+1,JA,J)))/(R*R)

	AY=V1(REAP(I))-V1(LINK(IA+1,JA,J))
	BY=(V1(REAP(I))-V1(LINK(IA+1,JA,J)))*(Y1(REAP(I))-Y1(LINK(IA+1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA+1,JA,J)))/(R*R)
	CY=(U1(REAP(I))-U1(LINK(IA+1,JA,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA+1,JA,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PM(LINK(IA+1,JA,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA+1,JA,J)))**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA+1,JA,J))+VIS0)*ROU(LINK(IA+1,JA,J)))

	DVVIS(REAP(I))=DVVIS(REAP(I))+PM(LINK(IA+1,JA,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA+1,JA,J)))**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA+1,JA,J))+VIS0)*ROU(LINK(IA+1,JA,J)))

	END DO
!!  NEIGHBOUR PARTICELS IN UPPER RIGHT GRID
	DO J=1,NLINK(IA+1,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA+1,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA+1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA+1,JA+1,J)))*(Y1(REAP(I))-Y1(LINK(IA+1,JA+1,J))))
	    IF(REAP(I)==LINK(IA+1,JA+1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF
!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))-U1(LINK(IA+1,JA+1,J))
	BX=(U1(REAP(I))-U1(LINK(IA+1,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA+1,J)))*&
       (X1(REAP(I))-X1(LINK(IA+1,JA+1,J)))/(R*R)
	CX=(V1(REAP(I))-V1(LINK(IA+1,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA+1,JA+1,J)))/(R*R)

	AY=V1(REAP(I))-V1(LINK(IA+1,JA+1,J))
	BY=(V1(REAP(I))-V1(LINK(IA+1,JA+1,J)))*(Y1(REAP(I))-Y1(LINK(IA+1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA+1,JA+1,J)))/(R*R)
	CY=(U1(REAP(I))-U1(LINK(IA+1,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA+1,JA+1,J)))/(R*R)
!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PM(LINK(IA+1,JA+1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA+1,JA+1,J)))**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA+1,JA+1,J))+VIS0)*ROU(LINK(IA+1,JA+1,J)))

	DVVIS(REAP(I))=DVVIS(REAP(I))+PM(LINK(IA+1,JA+1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA+1,JA+1,J)))**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA+1,JA+1,J))+VIS0)*ROU(LINK(IA+1,JA+1,J)))
	END DO
!!  NEIGHBOUR PARTICELS IN UPPER LEFT GRID
	DO J=1,NLINK(IA-1,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA-1,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA+1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA-1,JA+1,J)))*(Y1(REAP(I))-Y1(LINK(IA-1,JA+1,J))))
	    IF(REAP(I)==LINK(IA-1,JA+1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF
!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))-U1(LINK(IA-1,JA+1,J))
	BX=(U1(REAP(I))-U1(LINK(IA-1,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA+1,J)))*&
       (X1(REAP(I))-X1(LINK(IA-1,JA+1,J)))/(R*R)
	CX=(V1(REAP(I))-V1(LINK(IA-1,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA-1,JA+1,J)))/(R*R)

	AY=V1(REAP(I))-V1(LINK(IA-1,JA+1,J))
	BY=(V1(REAP(I))-V1(LINK(IA-1,JA+1,J)))*(Y1(REAP(I))-Y1(LINK(IA-1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA-1,JA+1,J)))/(R*R)
	CY=(U1(REAP(I))-U1(LINK(IA-1,JA+1,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA-1,JA+1,J)))/(R*R)
!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PM(LINK(IA-1,JA+1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA-1,JA+1,J)))**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA-1,JA+1,J))+VIS0)*ROU(LINK(IA-1,JA+1,J)))

	DVVIS(REAP(I))=DVVIS(REAP(I))+PM(LINK(IA-1,JA+1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA-1,JA+1,J)))**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA-1,JA+1,J))+VIS0)*ROU(LINK(IA-1,JA+1,J)))
	END DO
!!  NEIGHBOUR PARTICELS IN LOWER RIGHT GRID
	DO J=1,NLINK(IA+1,JA-1)
!!  PARTCLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA+1,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA-1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA+1,JA-1,J)))*(Y1(REAP(I))-Y1(LINK(IA+1,JA-1,J))))
	    IF(REAP(I)==LINK(IA+1,JA-1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF
!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))-U1(LINK(IA+1,JA-1,J))
	BX=(U1(REAP(I))-U1(LINK(IA+1,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA-1,J)))*&
       (X1(REAP(I))-X1(LINK(IA+1,JA-1,J)))/(R*R)
	CX=(V1(REAP(I))-V1(LINK(IA+1,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA+1,JA-1,J)))/(R*R)

	AY=V1(REAP(I))-V1(LINK(IA+1,JA-1,J))
	BY=(V1(REAP(I))-V1(LINK(IA+1,JA-1,J)))*(Y1(REAP(I))-Y1(LINK(IA+1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA+1,JA-1,J)))/(R*R)
	CY=(U1(REAP(I))-U1(LINK(IA+1,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA+1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA+1,JA-1,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PM(LINK(IA+1,JA-1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA+1,JA-1,J)))**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA+1,JA-1,J))+VIS0)*ROU(LINK(IA+1,JA-1,J)))

	DVVIS(REAP(I))=DVVIS(REAP(I))+PM(LINK(IA+1,JA-1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA+1,JA-1,J)))**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA+1,JA-1,J))+VIS0)*ROU(LINK(IA+1,JA-1,J)))

	END DO
!!  NEIGHBOUR PARTICELS IN LOWER LEFT GRID
	DO J=1,NLINK(IA-1,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINK(IA-1,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA-1,J)))+&
          (Y1(REAP(I))-Y1(LINK(IA-1,JA-1,J)))*(Y1(REAP(I))-Y1(LINK(IA-1,JA-1,J))))
	    IF(REAP(I)==LINK(IA-1,JA-1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF
!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))-U1(LINK(IA-1,JA-1,J))
	BX=(U1(REAP(I))-U1(LINK(IA-1,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA-1,J)))*&
       (X1(REAP(I))-X1(LINK(IA-1,JA-1,J)))/(R*R)
	CX=(V1(REAP(I))-V1(LINK(IA-1,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA-1,JA-1,J)))/(R*R)

	AY=V1(REAP(I))-V1(LINK(IA-1,JA-1,J))
	BY=(V1(REAP(I))-V1(LINK(IA-1,JA-1,J)))*(Y1(REAP(I))-Y1(LINK(IA-1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA-1,JA-1,J)))/(R*R)
	CY=(U1(REAP(I))-U1(LINK(IA-1,JA-1,J)))*(X1(REAP(I))-X1(LINK(IA-1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINK(IA-1,JA-1,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PM(LINK(IA-1,JA-1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA-1,JA-1,J)))**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA-1,JA-1,J))+VIS0)*ROU(LINK(IA-1,JA-1,J)))

	DVVIS(REAP(I))=DVVIS(REAP(I))+PM(LINK(IA-1,JA-1,J))*2.0*&
             (4.0/(ROU(REAP(I))+ROU(LINK(IA-1,JA-1,J)))**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             0.5*(VISEFF(LINK(IA-1,JA-1,J))+VIS0)*ROU(LINK(IA-1,JA-1,J)))

	END DO
!!  VELOCITY MODIFICATIONS BY USING DUMMY PARTICLES
!!  NEIGHBOUR PARTICELS IN CENTER GRID
	DO J=1,NLINKDUMMY(IA,JA)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA,JA,J)))**2+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!  USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF

!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))
	BX=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA,JA,J)))*&
       (X1(REAP(I))-X1(LINKDUMMY(IA,JA,J)))/(R*R)
	CX=V1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA,JA,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA,J)))/(R*R)

	AY=V1(REAP(I))
	BY=V1(REAP(I))*(Y1(REAP(I))-Y1(LINKDUMMY(IA,JA,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA,J)))/(R*R)
	CY=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA,JA,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	DVVIS(REAP(I))=DVVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	END DO
!!  NEIGHBOUR PARTICELS IN UPPER GRID
	DO J=1,NLINKDUMMY(IA,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA,JA+1,J)))**2+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA+1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF
!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))
	BX=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA,JA+1,J)))*&
       (X1(REAP(I))-X1(LINKDUMMY(IA,JA+1,J)))/(R*R)
	CX=V1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA+1,J)))/(R*R)

	AY=V1(REAP(I))
	BY=V1(REAP(I))*(Y1(REAP(I))-Y1(LINKDUMMY(IA,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA+1,J)))/(R*R)
	CY=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA+1,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	DVVIS(REAP(I))=DVVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)
	END DO

!!  NEIGHBOUR PARTICELS IN LOWER GRID
	DO J=1,NLINKDUMMY(IA,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA,JA-1,J)))**2+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA-1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF

!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))
	BX=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA,JA-1,J)))*&
       (X1(REAP(I))-X1(LINKDUMMY(IA,JA-1,J)))/(R*R)
	CX=V1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA-1,J)))/(R*R)

	AY=V1(REAP(I))
	BY=V1(REAP(I))*(Y1(REAP(I))-Y1(LINKDUMMY(IA,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA-1,J)))/(R*R)
	CY=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA,JA-1,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	DVVIS(REAP(I))=DVVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)
	END DO
!!  NEIGHBOUR PARTICELS IN LEFT GRID
	DO J=1,NLINKDUMMY(IA-1,JA)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA-1,JA,J)))**2+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF

!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))
	BX=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA-1,JA,J)))*&
       (X1(REAP(I))-X1(LINKDUMMY(IA-1,JA,J)))/(R*R)
	CX=V1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA-1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA,J)))/(R*R)

	AY=V1(REAP(I))
	BY=V1(REAP(I))*(Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA,J)))/(R*R)
	CY=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA-1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	DVVIS(REAP(I))=DVVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	END DO

!!  NEIGHBOUR PARTICELS IN RIGHT GRID
	DO J=1,NLINKDUMMY(IA+1,JA)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA+1,JA,J)))**2+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA,J)))**2)
	    IF(R.LE.(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF

!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))
	BX=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA+1,JA,J)))*&
       (X1(REAP(I))-X1(LINKDUMMY(IA+1,JA,J)))/(R*R)
	CX=V1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA+1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA,J)))/(R*R)

	AY=V1(REAP(I))
	BY=V1(REAP(I))*(Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA,J)))/(R*R)
	CY=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA+1,JA,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	DVVIS(REAP(I))=DVVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)
	END DO
!!  NEIGHBOUR PARTICELS IN UPPER-RIGHT GRID
	DO J=1,NLINKDUMMY(IA+1,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA+1,JA+1,J)))**2+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA+1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF

!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))
	BX=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA+1,JA+1,J)))*&
       (X1(REAP(I))-X1(LINKDUMMY(IA+1,JA+1,J)))/(R*R)
	CX=V1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA+1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA+1,J)))/(R*R)

	AY=V1(REAP(I))
	BY=V1(REAP(I))*(Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA+1,J)))/(R*R)
	CY=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA+1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA+1,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	DVVIS(REAP(I))=DVVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)
	END DO
!!  NEIGHBOUR PARTICELS IN UPPER-LEFT GRID
	DO J=1,NLINKDUMMY(IA-1,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA-1,JA+1,J)))**2+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA+1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF

!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))
	BX=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA-1,JA+1,J)))*&
       (X1(REAP(I))-X1(LINKDUMMY(IA-1,JA+1,J)))/(R*R)
	CX=V1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA-1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA+1,J)))/(R*R)

	AY=V1(REAP(I))
	BY=V1(REAP(I))*(Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA+1,J)))/(R*R)
	CY=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA-1,JA+1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA+1,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	DVVIS(REAP(I))=DVVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)
	END DO

!!  NEIGHBOUR PARTICELS IN LOWER-RIGHT GRID
	DO J=1,NLINKDUMMY(IA+1,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA+1,JA-1,J)))**2+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA-1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF

!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))
	BX=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA+1,JA-1,J)))*&
       (X1(REAP(I))-X1(LINKDUMMY(IA+1,JA-1,J)))/(R*R)
	CX=V1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA+1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA-1,J)))/(R*R)

	AY=V1(REAP(I))
	BY=V1(REAP(I))*(Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA-1,J)))/(R*R)
	CY=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA+1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA+1,JA-1,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	DVVIS(REAP(I))=DVVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)
	END DO
!!  NEIGHBOUR PARTICELS IN LOWER-LEFT GRID
	DO J=1,NLINKDUMMY(IA-1,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((X1(REAP(I))-X1(LINKDUMMY(IA-1,JA-1,J)))**2+&
          (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA-1,J)))**2)
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
        ELSE 
        CYCLE
	    END IF

!!  COMPUTING STRAIN IN X AND Y DIRECTION
	AX=U1(REAP(I))
	BX=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA-1,JA-1,J)))*&
       (X1(REAP(I))-X1(LINKDUMMY(IA-1,JA-1,J)))/(R*R)
	CX=V1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA-1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA-1,J)))/(R*R)

	AY=V1(REAP(I))
	BY=V1(REAP(I))*(Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA-1,J)))/(R*R)
	CY=U1(REAP(I))*(X1(REAP(I))-X1(LINKDUMMY(IA-1,JA-1,J)))*&
       (Y1(REAP(I))-Y1(LINKDUMMY(IA-1,JA-1,J)))/(R*R)

!!  MODIFIED VELOCITY BY NEIGHBOURING PARTICLES
	DUVIS(REAP(I))=DUVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AX+BX+CX)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	DVVIS(REAP(I))=DVVIS(REAP(I))+PMD*2.0*&
             (4.0/(ROU(REAP(I))+ROUDUMMY)**2)*DWDQ/&
             (H*R)*(AY+BY+CY)*(0.5*(VISEFF(REAP(I))+VIS0)*ROU(REAP(I))+&
             VIS0*ROUDUMMY)

	END DO

!!  COMPUTATION OF TEMPORAL VELOCITY AND COORDINATES
USTAR(REAP(I))=U1(REAP(I))+DUVIS(REAP(I))*DT
VSTAR(REAP(I))=V1(REAP(I))+G*DT+DVVIS(REAP(I))*DT
XSTAR(REAP(I))=X1(REAP(I))+0.5*(U1(REAP(I))+USTAR(REAP(I)))*DT
YSTAR(REAP(I))=Y1(REAP(I))+0.5*(V1(REAP(I))+VSTAR(REAP(I)))*DT

!! CHECK COURANT CONDICTION
A=XSTAR(REAP(I))-X1(REAP(I))
B=YSTAR(REAP(I))-Y1(REAP(I))
DISTANCE=SQRT(A*A+B*B)
    IF(DISTANCE>ALPHA*Sp) THEN
    WRITE(*,*)"TIME STEP TOO FAST IN PREDICTION! RETURN AND RESET DT!"
    ICHANGE=1
    RETURN
	END IF
END DO
!! TERMINATION OF PREDICTION STEP
RETURN
END SUBROUTINE predict