
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!     THIS SUBROUTINE DOES NOT NEED TO BE CHANGED     !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!! CALCULATION OF PARTICLE PRESSURE BY POISSON EQUATION
SUBROUTINE pressure
USE mdata
!! PARAMETERS FOR LINEAR EQUATION
!! RIGHT SOURCE VECTOR AND SOULUTION VECTOR(PRESSURE)
DOUBLE PRECISION B(NR)
!! TOTAL NUMBER OF NON-ZERO ELEMENTS IN MATRIX
INTEGER NZ
!! NON-ZERO ELEMENT IN MATRIX
DOUBLE PRECISION A(784000)
!! POSITION OF ROW AND COLUMN OF NON-ZERO ELEMENT IN MATRIX
INTEGER IROW(784000),JCOL(784000)
!! PARTICLE DISTANCE,RELATIVE DISTANCE AND KERNEL GRADIENT
DOUBLE PRECISION R,Q,DWDQ
!! DIAGONAL ELEMENT OF MATRIX
DOUBLE PRECISION DIAGONAL
!! TREATMENT OF SINGULAR PARTICLE--IF LESS THAN 4 IT IS SURFACE
NZ=0
DO I=1,NR
!!  TREATMENT OF FREE SURFACE
	IF(DENSTAR(REAP(I))<=ROUWATER) THEN
!!  NUMBER OF MATRIX ELEMENT
	NZ=NZ+1
!!  ELEMENT OF MATRIX
	A(NZ)=1.0
!!  SOURCE TERM
	B(I)=0.0
!!  POSITION NUMBER OF MATRIX ELEMENT
	IROW(NZ)=I
	JCOL(NZ)=I
	CYCLE
    END IF

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!  FORMATION OF PARAMETERS	FOR LINEAR EQUATION.....  !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  INITIALIZATION OF DIAGONAL ELEMENTS
DIAGONAL=0.0
!! FORMATION OF NON-DIAGONAL ELEMENTS
!! NEIGHBOUR PARTICELS IN CENTER GRID
IA=XSTAR(REAP(I))/(2.0*H)
JA=YSTAR(REAP(I))/(2.0*H)
	DO J=1,NLINK(IA,JA)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA,JA,J)))*&
          (XSTAR(REAP(I))-XSTAR(LINK(IA,JA,J)))+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA,JA,J)))*&
          (YSTAR(REAP(I))-YSTAR(LINK(IA,JA,J))))
!!      EXCLUDING REFERENCE PARTICLE
	    IF(REAP(I)==LINK(IA,JA,J)) CYCLE
!!      AVOIDING SINGULARITY
	    IF(R<=(0.1*H)) R=0.1*H
!!  RELATIVE DISTANCE
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	NZ=NZ+1
	A(NZ)=8.0*PM(LINK(IA,JA,J))*DWDQ/(H*R)/&
          ((ROU(REAP(I))+ROU(LINK(IA,JA,J)))**2)
!!      TREATMENT OF WALL PARTCILES TO SATISFY NEUMANN BOUDNARY
	    IF(IFLAG(REAP(I))==1.AND.IFLAG(LINK(IA,JA,J))==2) A(NZ)=2.0*A(NZ)
        IF(IFLAG(REAP(I))==3.AND.IFLAG(LINK(IA,JA,J))==2) A(NZ)=2.0*A(NZ)
	IROW(NZ)=I
        DO K=1,NR
        IF(REAP(K)==LINK(IA,JA,J)) THEN
        JCOL(NZ)=K
        ELSE
        ENDIF
    END DO
	DIAGONAL=DIAGONAL+A(NZ)
	END DO
!!  NEIGHBOUR PARTICELS IN UPPER GRID
	DO J=1,NLINK(IA,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA,JA+1,J)))*&
          (XSTAR(REAP(I))-XSTAR(LINK(IA,JA+1,J)))+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA,JA+1,J)))*&
          (YSTAR(REAP(I))-YSTAR(LINK(IA,JA+1,J))))
	    IF(REAP(I)==LINK(IA,JA+1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	NZ=NZ+1
	A(NZ)=8.0*PM(LINK(IA,JA+1,J))*DWDQ/(H*R)/&
          ((ROU(REAP(I))+ROU(LINK(IA,JA+1,J)))**2)
!!      TREATMENT OF WALL PARTCILES TO SATISFY NEUMANN BOUDNARY
	    IF(IFLAG(REAP(I))==1.AND.IFLAG(LINK(IA,JA+1,J))==2) A(NZ)=2.0*A(NZ)
        IF(IFLAG(REAP(I))==3.AND.IFLAG(LINK(IA,JA+1,J))==2) A(NZ)=2.0*A(NZ)
	IROW(NZ)=I
    DO K=1,NR
        IF(REAP(K)==LINK(IA,JA+1,J)) THEN
        JCOL(NZ)=K
        ELSE
        ENDIF
    END DO
	
	DIAGONAL=DIAGONAL+A(NZ)
	END DO
!!  NEIGHBOUR PARTICELS IN LOWER GRID
	DO J=1,NLINK(IA,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA,JA-1,J)))*&
          (XSTAR(REAP(I))-XSTAR(LINK(IA,JA-1,J)))+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA,JA-1,J)))*&
          (YSTAR(REAP(I))-YSTAR(LINK(IA,JA-1,J))))
	    IF(REAP(I)==LINK(IA,JA-1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	NZ=NZ+1
	A(NZ)=8.0*PM(LINK(IA,JA-1,J))*DWDQ/(H*R)/&
          ((ROU(REAP(I))+ROU(LINK(IA,JA-1,J)))**2)
!!      TREATMENT OF WALL PARTCILES TO SATISFY NEUMANN BOUDNARY
	    IF(IFLAG(REAP(I))==1.AND.IFLAG(LINK(IA,JA-1,J))==2) A(NZ)=2.0*A(NZ)
        IF(IFLAG(REAP(I))==3.AND.IFLAG(LINK(IA,JA-1,J))==2) A(NZ)=2.0*A(NZ)
	IROW(NZ)=I
	    DO K=1,NR
        IF(REAP(K)==LINK(IA,JA-1,J)) THEN
        JCOL(NZ)=K
        ELSE
        ENDIF
    END DO
	DIAGONAL=DIAGONAL+A(NZ)
	END DO
!!  NEIGHBOUR PARTICELS IN LEFT GRID
	DO J=1,NLINK(IA-1,JA)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA,J)))*&
          (XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA,J)))+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA,J)))*&
          (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA,J))))
	    IF(REAP(I)==LINK(IA-1,JA,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	NZ=NZ+1
	A(NZ)=8.0*PM(LINK(IA-1,JA,J))*DWDQ/(H*R)/&
          ((ROU(REAP(I))+ROU(LINK(IA-1,JA,J)))**2)
!!      TREATMENT OF WALL PARTCILES TO SATISFY NEUMANN BOUDNARY
	    IF(IFLAG(REAP(I))==1.AND.IFLAG(LINK(IA-1,JA,J))==2) A(NZ)=2.0*A(NZ)
        IF(IFLAG(REAP(I))==3.AND.IFLAG(LINK(IA-1,JA,J))==2) A(NZ)=2.0*A(NZ)
	IROW(NZ)=I
    DO K=1,NR
        IF(REAP(K)==LINK(IA-1,JA,J)) THEN
        JCOL(NZ)=K
        ELSE
        ENDIF
    END DO
	DIAGONAL=DIAGONAL+A(NZ)
	END DO
!!  NEIGHBOUR PARTICELS IN RIGHT GRID
	DO J=1,NLINK(IA+1,JA)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA,J)))*&
          (XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA,J)))+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA,J)))*&
          (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA,J))))
	    IF(REAP(I)==LINK(IA+1,JA,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
        IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
   	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	NZ=NZ+1
	A(NZ)=8.0*PM(LINK(IA+1,JA,J))*DWDQ/(H*R)/&
          ((ROU(REAP(I))+ROU(LINK(IA+1,JA,J)))**2)
!!      TREATMENT OF WALL PARTCILES TO SATISFY NEUMANN BOUDNARY
	    IF(IFLAG(REAP(I))==1.AND.IFLAG(LINK(IA+1,JA,J))==2) A(NZ)=2.0*A(NZ)
        IF(IFLAG(REAP(I))==3.AND.IFLAG(LINK(IA+1,JA,J))==2) A(NZ)=2.0*A(NZ)
	IROW(NZ)=I
	DO K=1,NR
        IF(REAP(K)==LINK(IA+1,JA,J)) THEN
        JCOL(NZ)=K
        ELSE
        ENDIF
    END DO
	DIAGONAL=DIAGONAL+A(NZ)
	END DO
!!  NEIGHBOUR PARTICELS IN UPPER RIGHT GRID
	DO J=1,NLINK(IA+1,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA+1,J)))*&
          (XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA+1,J)))+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA+1,J)))*&
          (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA+1,J))))
	    IF(REAP(I)==LINK(IA+1,JA+1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	NZ=NZ+1
	A(NZ)=8.0*PM(LINK(IA+1,JA+1,J))*DWDQ/(H*R)/&
          ((ROU(REAP(I))+ROU(LINK(IA+1,JA+1,J)))**2)
!!      TREATMENT OF WALL PARTCILES TO SATISFY NEUMANN BOUDNARY
	    IF(IFLAG(REAP(I))==1.AND.IFLAG(LINK(IA+1,JA+1,J))==2) A(NZ)=2.0*A(NZ)
        IF(IFLAG(REAP(I))==3.AND.IFLAG(LINK(IA+1,JA+1,J))==2) A(NZ)=2.0*A(NZ)
	IROW(NZ)=I
	DO K=1,NR
        IF(REAP(K)==LINK(IA+1,JA+1,J)) THEN
        JCOL(NZ)=K
        ELSE
        ENDIF
    END DO
	DIAGONAL=DIAGONAL+A(NZ)
    END DO
!!  NEIGHBOUR PARTICELS IN UPPER LEFT GRID
	DO J=1,NLINK(IA-1,JA+1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA+1,J)))*&
          (XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA+1,J)))+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA+1,J)))*&
          (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA+1,J))))
	    IF(REAP(I)==LINK(IA-1,JA+1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!	    USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
   	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	NZ=NZ+1
	A(NZ)=8.0*PM(LINK(IA-1,JA+1,J))*DWDQ/(H*R)/&
          ((ROU(REAP(I))+ROU(LINK(IA-1,JA+1,J)))**2)
!!      TREATMENT OF WALL PARTCILES TO SATISFY NEUMANN BOUDNARY
	    IF(IFLAG(REAP(I))==1.AND.IFLAG(LINK(IA-1,JA+1,J))==2) A(NZ)=2.0*A(NZ)
        IF(IFLAG(REAP(I))==3.AND.IFLAG(LINK(IA-1,JA+1,J))==2) A(NZ)=2.0*A(NZ)
	IROW(NZ)=I
	DO K=1,NR
        IF(REAP(K)==LINK(IA-1,JA+1,J)) THEN
        JCOL(NZ)=K
        ELSE
        ENDIF
    END DO
	DIAGONAL=DIAGONAL+A(NZ)
	END DO
!!  NEIGHBOUR PARTICELS IN LOWER RIGHT GRID
	DO J=1,NLINK(IA+1,JA-1)
!!  PARTICLE DISTANCE
	R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA-1,J)))*&
          (XSTAR(REAP(I))-XSTAR(LINK(IA+1,JA-1,J)))+&
          (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA-1,J)))*&
          (YSTAR(REAP(I))-YSTAR(LINK(IA+1,JA-1,J))))
	    IF(REAP(I)==LINK(IA+1,JA-1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!      USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>=1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	NZ=NZ+1
	A(NZ)=8.0*PM(LINK(IA+1,JA-1,J))*DWDQ/(H*R)/&
          ((ROU(REAP(I))+ROU(LINK(IA+1,JA-1,J)))**2)
!!      TREATMENT OF WALL PARTCILES TO SATISFY NEUMANN BOUDNARY
	    IF(IFLAG(REAP(I))==1.AND.IFLAG(LINK(IA+1,JA-1,J))==2) A(NZ)=2.0*A(NZ)
        IF(IFLAG(REAP(I))==3.AND.IFLAG(LINK(IA+1,JA-1,J))==2) A(NZ)=2.0*A(NZ)
	IROW(NZ)=I
	DO K=1,NR
        IF(REAP(K)==LINK(IA+1,JA-1,J)) THEN
        JCOL(NZ)=K
        ELSE
        ENDIF
    END DO
	DIAGONAL=DIAGONAL+A(NZ)
	END DO
!!  NEIGHBOUR PARTICELS IN LOWER LEFT GRID
	DO J=1,NLINK(IA-1,JA-1)
!!  PARTICLE DISTANCE
	 R=SQRT((XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA-1,J)))*&
           (XSTAR(REAP(I))-XSTAR(LINK(IA-1,JA-1,J)))+&
           (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA-1,J)))*&
           (YSTAR(REAP(I))-YSTAR(LINK(IA-1,JA-1,J))))
	    IF(I==LINK(IA-1,JA-1,J)) CYCLE
	    IF(R<=(0.1*H)) R=0.1*H
	Q=R/H
!!  	USING DIFFERENT	KERNELS ACCORDING TO DIFFERENT PARTICLE DISTANCES
	    IF(Q<=1.0) THEN
	    DWDQ=-30.0*Q*(1.0-0.75*Q)/(7.0*3.141*H*H)
	    ELSEIF(Q>1.0.AND.Q<=2.0) THEN
	    DWDQ=-30.0*(2.0-Q)*(2.0-Q)/(28.0*3.141*H*H)
	    ELSE
		CYCLE
	    END IF
	NZ=NZ+1
	A(NZ)=8.0*PM(LINK(IA-1,JA-1,J))*DWDQ/(H*R)/&
          ((ROU(REAP(I))+ROU(LINK(IA-1,JA-1,J)))**2)
!!      TREATMENT OF WALL PARTCILES TO SATISFY NEUMANN BOUDNARY
	    IF(IFLAG(REAP(I))==1.AND.IFLAG(LINK(IA-1,JA-1,J))==2) A(NZ)=2.0*A(NZ)
        IF(IFLAG(REAP(I))==3.AND.IFLAG(LINK(IA-1,JA-1,J))==2) A(NZ)=2.0*A(NZ)
	IROW(NZ)=I
	DO K=1,NR
        IF(REAP(K)==LINK(IA-1,JA-1,J)) THEN
        JCOL(NZ)=K
        ELSE
        ENDIF
    END DO
	DIAGONAL=DIAGONAL+A(NZ)
	END DO
!!  CALCULATION OF DIAGONAL ELEMENTS(¶Ô½ÇÔªËØ)
NZ=NZ+1
A(NZ)=-DIAGONAL+1.0E-6/DT/DT
IROW(NZ)=I
JCOL(NZ)=I

!!SOURCE TERM
    B(I)=(-DEN0(I)+DENSTAR(I))/(ROU(I)*DT*DT)
	IF(DEN0(I)<=ROUWATER) THEN
    B(I)=(-ROUWATER+DENSTAR(I))/(ROU(I)*DT*DT)
    END IF

END DO

!! SOLUTION OF LINEAR EQUATION BY SOLVER
CALL BICG(NR,NZ,A,IROW,JCOL,B,P)
!! negative pressure is not desired to ensure numerical stability
DO I=1,NR
    P(REAP(I))=P(I)
	IF(P(REAP(I))<0.0) P(REAP(I))=0.0
END DO
!! END OF PRESSURE EQUATION SOLUTION
RETURN
END SUBROUTINE pressure